version: "2"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-tier

  backend:
    depends_on:
      - redis
    build: .
    ports:
      - '8080:8080'
      - '5300:5300'
    networks:
      - app-tier
